import { Announcement, Member } from '../models/types'

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 1,
    title: 'Compétition de ski — Oukaïmeden 2026',
    body: 'Nous sommes ravis d\'annoncer la 3ème édition de notre compétition annuelle de ski à Oukaïmeden. Tous les membres du club ski sont invités à participer. Inscription obligatoire avant le 20 avril. Matériel fourni pour les moins de 16 ans.',
    category: 'competition',
    club: 'ski',
    author: { id: 1, firstName: 'Ahmed', lastName: 'Bouserhan' },
    pinned: true,
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-04-10T09:00:00Z',
  },
  {
    id: 2,
    title: 'Tournoi de football Ramadan — Résultats',
    body: 'Félicitations à toute l\'équipe pour leur victoire au tournoi de football du Ramadan ! Un grand merci aux supporters et aux familles présentes. Les photos seront publiées sur notre page Facebook.',
    category: 'evenement',
    club: 'football',
    author: { id: 1, firstName: 'Ahmed', lastName: 'Bouserhan' },
    pinned: false,
    createdAt: '2026-04-08T14:30:00Z',
    updatedAt: '2026-04-08T14:30:00Z',
  },
  {
    id: 3,
    title: 'Entraînement athlétisme — Nouveau programme',
    body: 'Le nouveau programme d\'entraînement pour la saison printemps-été est disponible. Les séances auront lieu le mardi et jeudi de 17h à 19h. Présentez-vous avec votre tenue sportive.',
    category: 'entrainement',
    club: 'athletisme',
    author: { id: 2, firstName: 'Jamila', lastName: 'Chenter' },
    pinned: false,
    createdAt: '2026-04-07T10:00:00Z',
    updatedAt: '2026-04-07T10:00:00Z',
  },
  {
    id: 4,
    title: 'Réunion générale — Assemblée annuelle',
    body: 'L\'assemblée générale annuelle de l\'ASATA se tiendra le samedi 25 avril à 10h au siège du club. La présence de tous les membres est vivement souhaitée. Ordre du jour : bilan 2025, projets 2026, renouvellement du bureau.',
    category: 'general',
    club: 'all',
    author: { id: 1, firstName: 'Ahmed', lastName: 'Bouserhan' },
    pinned: true,
    createdAt: '2026-04-05T08:00:00Z',
    updatedAt: '2026-04-05T08:00:00Z',
  },
  {
    id: 5,
    title: '⚠️ Annulation séance — Conditions météo',
    body: 'En raison des mauvaises conditions météorologiques prévues ce weekend, la séance de ski du samedi 13 avril est annulée. Elle sera reprogrammée la semaine prochaine. Soyez prudents.',
    category: 'urgent',
    club: 'ski',
    author: { id: 1, firstName: 'Ahmed', lastName: 'Bouserhan' },
    pinned: false,
    createdAt: '2026-04-04T18:00:00Z',
    updatedAt: '2026-04-04T18:00:00Z',
  },
]

export const MOCK_MEMBERS: Member[] = [
  { id: 1,  firstName: 'Ahmed',      lastName: 'Bouserhan',      email: 'ahmed@asata.ma',      phone: '+212 661 000 001', club: 'ski',        role: 'admin',  active: true,  joinedAt: '2010-05-01' },
  { id: 2,  firstName: 'Jamila',     lastName: 'Chenter',        email: 'jamila@asata.ma',     phone: '+212 661 000 002', club: 'athletisme', role: 'admin',  active: true,  joinedAt: '2012-03-15' },
  { id: 3,  firstName: 'Farid',      lastName: 'Bouserhan',      email: 'farid@asata.ma',      phone: '+212 661 000 003', club: 'ski',        role: 'member', active: true,  joinedAt: '2015-09-01' },
  { id: 4,  firstName: 'Abd Essamad',lastName: 'Ait Bel Haj',    email: 'abd@asata.ma',        phone: '+212 661 000 004', club: 'football',   role: 'member', active: true,  joinedAt: '2016-01-10' },
  { id: 5,  firstName: 'Mohamed',    lastName: 'Ait Chakart',    email: 'med.chakart@asata.ma',phone: '+212 661 000 005', club: 'ski',        role: 'member', active: true,  joinedAt: '2017-11-20' },
  { id: 6,  firstName: 'Mohamed',    lastName: 'Aourik',         email: 'med.aourik@asata.ma', phone: '+212 661 000 006', club: 'football',   role: 'member', active: true,  joinedAt: '2018-06-05' },
  { id: 7,  firstName: 'Nora',       lastName: 'Achebani',       email: 'nora@asata.ma',       phone: '+212 661 000 007', club: 'athletisme', role: 'member', active: true,  joinedAt: '2019-02-14' },
  { id: 8,  firstName: 'Rachid',     lastName: 'Bouserhan',      email: 'rachid@asata.ma',     phone: '+212 661 000 008', club: 'ski',        role: 'member', active: true,  joinedAt: '2020-08-30' },
  { id: 9,  firstName: 'Mohamed',    lastName: 'El Aouad',       email: 'med.aouad@asata.ma',  phone: '+212 661 000 009', club: 'football',   role: 'member', active: false, joinedAt: '2021-03-12' },
  { id: 10, firstName: 'Aziz',       lastName: 'Ait Bourhim',    email: 'aziz@asata.ma',       phone: '+212 661 000 010', club: 'athletisme', role: 'member', active: true,  joinedAt: '2021-07-01' },
  { id: 11, firstName: 'Elmajid',    lastName: 'Oussais',        email: 'elmajid@asata.ma',    phone: '+212 661 000 011', club: 'ski',        role: 'member', active: true,  joinedAt: '2022-01-15' },
]
