import { StyleSheet } from 'react-native';

import { Colors } from '../../constants/colors';
import { Spacing } from '../../constants/spacing';
import { FontSize, FontWeight } from '../../constants/typography';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  hero: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.container,
    paddingTop: Spacing.xl,
    paddingBottom: 64,
    overflow: 'hidden',
  },
  avatarRing: {
    position: 'relative',
    width: 86,
    height: 86,
    borderRadius: 43,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: Colors.surface,
    marginBottom: Spacing.lg,
  },
  onlineDot: {
    position: 'absolute',
    right: 0,
    bottom: 8,
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 4,
    borderColor: Colors.primary,
    backgroundColor: '#2EE66B',
  },
  name: {
    color: Colors.surface,
    fontSize: FontSize.display,
    fontWeight: FontWeight.bold,
    textAlign: 'center',
  },
  badgeRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  roleBadge: {
    borderRadius: 9999,
    backgroundColor: Colors.whiteOverlay20,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  roleText: {
    color: Colors.surface,
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    textTransform: 'uppercase',
  },
  activeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    borderRadius: 9999,
    backgroundColor: Colors.whiteOverlay20,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2EE66B',
  },
  activeText: {
    color: '#2EE66B',
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    letterSpacing: 0.96,
    textTransform: 'uppercase',
  },
  stats: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginTop: -44,
    marginBottom: Spacing.lg,
    paddingHorizontal: Spacing.container,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: Colors.surface,
    paddingVertical: Spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    gap: Spacing.xs,
  },
  statNumber: {
    color: Colors.primaryDark,
    fontSize: FontSize.h2,
    fontWeight: FontWeight.bold,
  },
  statLabel: {
    color: Colors.textSecondary,
    fontSize: FontSize.tab,
    letterSpacing: 0.96,
  },
  content: {
    gap: Spacing.md,
    paddingBottom: 96,
  },
  infoCard: {
    borderRadius: 12,
    backgroundColor: Colors.surface,
    marginHorizontal: Spacing.container,
    padding: Spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    color: Colors.textSecondary,
    fontSize: FontSize.xl,
    fontWeight: FontWeight.regular,
    letterSpacing: 1.6,
    marginBottom: Spacing.md,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    minHeight: 72,
  },
  infoRowLast: {
    borderBottomWidth: 0,
  },
  infoIcon: {
    width: 50,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(66,165,245,0.10)',
  },
  infoCopy: {
    flex: 1,
  },
  infoLabel: {
    color: Colors.textSecondary,
    fontSize: FontSize.sm,
  },
  infoValue: {
    color: Colors.textPrimary,
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    marginTop: 2,
  },
  securityRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: Colors.divider,
  },
  securityLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  securityText: {
    color: Colors.textPrimary,
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
  },
});
